### ISSUE TITLE
Rename extension on GitHub and change Maven coordinates

### ISSUE THREAD

**Issue by celanthe** [camunda-community-hub/camunda-platform-7-process-test-coverage#190]
Hi Simon,

This issue is being opened to let you know that your extension will need to be renamed here on GitHub via the 'Settings' option to reference Camunda Platform 7 rather than Camunda BPM. if you have any questions or require any assistance, please do not hesitate to reach out to @camunda-community-hub/devrel! :) You can also make use of [Shields.io badges](https://github.com/camunda-community-hub/community/blob/main/extension-lifecycle.md) to indicate which version of Camunda your extension is compatible with.

**Comment by akeller** [comment]
Hi @zambrovski is this something you can take care of or are interested in doing? If renaming the entire project is too difficult, I would at least recommend renaming Camunda BPM to Camunda Platform 7 in the README and adding the badge.

**Comment by zambrovski** [comment]
Will do.. please let me wait until after the CCS2022

**Comment by akeller** [comment]
Of course 😄

**Comment by zambrovski** [comment]
By the way, somehow, I'm missing most permissions in "settings" could you please check and provide them back to me?

**Comment by akeller** [comment]
I went ahead and gave you `admin` level for this repo.

**Comment by zambrovski** [comment]
Do we need to change Maven Coordinates too? Currently they are 


    <groupId>org.camunda.bpm.extension</groupId>
    <artifactId>camunda-bpm-process-test-coverage-junit4</artifactId>

**Comment by akeller** [comment]
I believe those are still the same, but I'm tagging in @berndruecker to help confirm 😄

**Comment by zambrovski** [comment]
I'll change them too.
